### ISSUE TITLE
Please consider to switch to python 3.x

### ISSUE THREAD

**Issue by epico** [googlefonts/nototools#472]
Currently we are switching to python 3.x in Fedora, please consider to switch nototools to use python 3.x.

Thanks in advance!

**Comment by PureTryOut** [comment]
More and more distributions are dropping Python 2 since it's going to be end of life soon. Please consider dropping Python 2 support soon and switching to Python 3!

**Comment by ILMostro** [comment]
third-party tools still need to be ported; e.g. spiro and fontcrunch.
