### ISSUE TITLE
OS X install error: "Error: invalid option: --with-cairo"

### ISSUE THREAD

**Issue by RoelN** [googlefonts/nototools#485]
Running the command from the readme:

`brew install --with-cairo harfbuzz cairo pango pygtk imagemagick`

fails with with the error:

`Error: invalid option: --with-cairo`

I'm on Mac OS 10.13.6, brew version is 2.1.4

**Comment by anthrotype** [comment]
I think this is because homebrew has been deprecating the use of build options lately. Does it work if you don't pass that option? I think so.

**Comment by RoelN** [comment]
The install seems okay, no errors or warnings in the output. I can run `notodiff` fine.

Heading over to Noto Emoji and running `make` results in the following error, though:

```
~/noto-emoji master 15:48:23 [dreamcast]
$ make
using optipng
cc waveflag.c -o waveflag -std=c99 -Wall -Wextra `pkg-config --cflags --libs cairo` -lm `pkg-config --libs cairo`
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
waveflag.c:19:10: fatal error: 'cairo.h' file not found
#include <cairo.h>
         ^~~~~~~~~
1 error generated.
make: *** [waveflag] Error 1
```

**Comment by anthrotype** [comment]
that's an issue for noto-emoji rather than nototools repository I guess. Can you reopen the issue over there?

BTW, I would try `brew install libffi`

**Comment by RoelN** [comment]
@anthrotype I assumed since the error was about Cairo, this `--with-cairo` thing was to blame. Re-installing `libffi` fixed the issue.

Thanks for the pointers! 🙏
