### ISSUE TITLE
 Need update Noto fonts on google.com/get/noto.

### ISSUE THREAD

**Issue by ghost** [googlefonts/nototools#525]
The fonts available on google.com/get/noto are already obsolete.

https://www.google.com/get/noto/updates/

The update history stopped in 2017 but Noto's latest version is v20201206.

https://github.com/googlefonts/noto-fonts/releases/tag/v20201206-phase3
https://github.com/googlefonts/noto-cjk/releases/tag/v20201206-cjk

**Comment by simoncozens** [comment]
This has been replaced by a new Noto web site, so I think this is now fixed.
